kairos:
  domain: <YOUR ZENDESK SUB DOMAIN GOES HERE>
  auth: Basic <YOUR BASE64 ENCODED STRING CONTAINING THE ADMIN USER EMAIL AND API TOKEN GOES HERE>

kairos-sb:
  domain: <YOUR ZENDESK SUB DOMAIN GOES HERE>
  auth: Basic <YOUR BASE64 ENCODED STRING CONTAINING THE ADMIN USER EMAIL AND API TOKEN GOES HERE>